# Generated by Django 4.2.8 on 2024-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("pan", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("maritial_status", models.CharField(max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("general", "General User"),
                            ("officer", "Government Officer"),
                            ("super_admin", "Super Admin"),
                        ],
                        default="general",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "db_table": "auth_users",
            },
        ),
    ]
