# Generated by Django 4.2.8 on 2024-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_maritial_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reward_points",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
