# Generated by Django 4.2.8 on 2024-05-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_annual_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=2595),
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Koshi", "Koshi"),
                    ("Madesh", "Madesh"),
                    ("Bagmati", "Bagmati"),
                    ("Gandaki", "Gandaki"),
                    ("Lumbini", "Lumbini"),
                    ("Karnali", "Karnali"),
                    ("Sudurpaschim", "Sudurpaschim"),
                ],
                max_length=50,
            ),
        ),
    ]
