# Generated by Django 4.2.8 on 2024-04-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0002_alter_fiscalyear_meta_alter_incometaxrecord_meta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fiscalyear",
            old_name="year",
            new_name="initiate_date",
        ),
        migrations.AlterField(
            model_name="fiscalyear",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
