# Generated by Django 4.2.8 on 2024-05-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0006_vehicletaxrecord_vehicletaxpolicy_corporatetaxrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalyear",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
    ]
