# Generated by Django 4.2.8 on 2024-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0007_fiscalyear_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="incometaxpolicy",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
    ]
